### ISSUE TITLE
HW2 void archive(char** filenames, int numFiles, char* archivename)

### ISSUE THREAD

**Issue by doug-skinner** [doug-skinner/csi_402_systems_programming#1]

**Comment by SherriLewis** [comment]
I assume with this we get the parameters from the arguments and then we just have to use the struct to build the archive file by writing to a file that we create with the archive name?

**Comment by doug-skinner** [comment]
That's it exactly

**Comment by SherriLewis** [comment]
I'll start this but we have dinner at 6 so I'll get back to it after that. It's getting easier but I'm sure my last function had issues with the code. BRB

**Comment by SherriLewis** [comment]
oh and I assume that if I include the struct.h file at the top I can use the struct without doing anything else?
Is there a specific way that it has to be defined when it's not a standard library but one that is created?

**Comment by SherriLewis** [comment]
Take a look at what I did. I'm feeling like I'm forgetting a lot because I feel like there isn't much to this function. I didn't add any error checking because I figured that can be done better in a separate function correct?
[archive.zip](https://github.com/doug-skinner/csi_402_systems_programming/files/1425759/archive.zip)
